### ISSUE TITLE
[Bug] Ticking Entity Error

### ISSUE THREAD

**Issue by Cyranos** [txnimc/SodiumDynamicLights#11] opened 2024-09-16 22:39 UTC
To note I am not certain is actually ticking entity, though the first crash log I got was for the local player; [here](https://mclo.gs/NCqbiKa) and the second one I got was for a bat entity apparently; [here](https://mclo.gs/3qxoddT)

**Comment by muon-rw** [comment] 2024-09-18 17:57
Caused by Ars Nouveau

**Comment by nthxny** [comment] 2024-09-22 16:42
should be fixed in latest update.

**Closed by nthxny** 2024-09-22 16:42 UTC
